name: Run Python Script and Push Output

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install newest Git
        run: |
          sudo apt-get update
          sudo apt-get install git -y

      - name: Clone TitleDB
        run: |
          git clone --depth 1 https://github.com/blawar/titledb.git

      - name: Run Python script
        run: python script.py

      - name: Push new files to repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add --ignore-removal output/
          git add --ignore-removal output2/
          timestamp=$(date -u)
          git commit -m "Last update: ${timestamp}" || exit 0
          git push
